bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/index.html, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/modalBuildViewer.htm, bnd-workspace/de.fraunhofer.abm.app/web/filters/TabTitleFilter.js
Added collection name on hover in html files top the tabs, removed
"Building" from the tab that was being prepended in the javascript file
=> Improvement to Build Tabs on BuildView Modal and Index.

bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/index.html, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/view.htm
Updated the button sizes on the footer (underneath the table) for public
collections to be consistent with others. Updated the text from
'Automatic' to 'Automated' on the header and in the tab title (tab title
being the browser tab)
=> Fixes to Issue 41 and 33 - Button sizes and 'Automatic' to 'Automated'

bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/editCollection.htm, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/my.htm
=> Fixing english syntax on the website

bnd-workspace/de.fraunhofer.abm.app/web/style.css
This match fixes the orientation change done in [#14]
=> [#78] Corners of the side tab to the left

bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/index.html
Screenshot:
Sorry it took a bit longer to get up - busy week and noticed there was still a resizing issue from my original fix since the last meeting
=> Title fix Tested with wide screen and narrow screen

bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/editCollection.htm, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/view.htm
Added a new css file to manage the styling for mandatory fields
=> Css changes

bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/index.html
Changes made in one file 'index.htlm' to solving the issue 93. We have increase the margin-top of the div from 89px to 100px.
<div style="margin-top:100px;position:relative" ng-view></div>
=> solving of Issue 93: Responsive design

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CollectionController.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/CollectionControllerTest.java
Added the ability to query the backend for the last successfully built version for a particular collection, as stated in issue #83. 
Since i need built versions to test my feature, i introduced a UnitTest that builds a version of a specific project via REST interface. This test does pass, but takes a lot of time (about 1~2 mins) and won't scale well, especially since i would like to extend the testing to catch more corner cases. Is this generally speaking the right way to go, or is there a better way to mock successful build results without actually building a project?
=> Added capability to query last successfully built version

bnd-workspace/de.fraunhofer.abm.test.http/checkstyle.xml, bnd-workspace/de.fraunhofer.abm.test.http/pom.xml, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/AbstractHttpTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/CollectionControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/CommitControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/CommitSelectionControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/CriteriaFilterControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/LoginTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/TestParameters.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/VersionControllerTest.java
VersionControllerTest.java
magic num
AbstractHttpTest.java
magic num
final parameters
line length
CommitSelectionControllerTest.java
magic num
line length
CommitControllerTest.java
magic num
CollectionControllerTest.java
magic num
line length
TestParameters.java
add methods to interface
CriteriaFilterControllerTest.java
line length
=> Checkstyle check and fixes for java files.

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUser.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/UserDTO.java, docs/abm.sql
=> Anitha usermgmt

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java
userDao.addUser code fix - missing parameters
=> userDao.addUser code fix - missing parameters

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.app/web/controllers/RegistrationController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUser.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/UserDTO.java
User registration and edit user profile related changes to develop branch
=> User registration and edit user profile to develop branch

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/AbmApplication.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/BuildController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CollectionController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CommitController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/HermesController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/PinController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserDelController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/VersionController.java, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/home.htm, bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.security/src/de/fraunhofer/abm/app/auth/Authorizer.java, bnd-workspace/de.fraunhofer.abm.security/src/de/fraunhofer/abm/app/auth/impl/UserAdminAuthorizer.java
DeleteUser(roles table) and Login for Admin
Delete User details from roles table
Delete user should delete all user related data from user, role, roles_properties, roles_members table.
https://github.com/ABenchM/abm/issues/186
Login for "Registered User" and "User Admin"
Authorizer changes made by Anitha.
https://github.com/ABenchM/abm/issues/185
=> Delete User roles table(by Anu) and Login for Admin(by Anitha)

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UnlockUserController.java, bnd-workspace/de.fraunhofer.abm.app/web/controllers/UnlockUserController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java
Issue: https://github.com/ABenchM/abm/issues/166
Code changes for admin, lock and unlock users
@Chinmay-92 
@anut347 
Please review changes
=> Lock and Unlock user

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java
=> Changes wrt update user

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/AdminUserDeleteController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserDelController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserDeleteController.java, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/home.htm, bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/CollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java
- Delete all pinned collections entry for the user(s).
- Delete private collections of the user when user deletes his/her account or when admin deletes user accounts.
- Update the user to demo for public collections of that user.
Changes in AdminUserDeleteController.java, UserDeleteController.java, JpaCollectionDao.java, JpaUserDao.java, CollectionDao.java, UserDao.java.
Code changes for:
https://github.com/ABenchM/abm/issues/191
https://github.com/ABenchM/abm/issues/192
https://github.com/ABenchM/abm/issues/198
=> Delete User(s) and handling user collections

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/DeletePublicCollectionController.java
code is tested after integrating with UI
=> method is changed from http post to http delete

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/ActiveCollectionController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UpdateRoleController.java, bnd-workspace/de.fraunhofer.abm.app/web/controllers/ActiveCollectionController.js, bnd-workspace/de.fraunhofer.abm.app/web/controllers/RoleUpdateController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollection.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/CollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/CollectionDTO.java
@anut347
@Chinmay-92
Please review the changes for
1)Update Role
#166
2)Activate/Deactivate public collection
#196
For 2) test html code
Reset Password
ss="form-actions text-right">
Submit
=> Anitha adminmgmt

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserDetailsController.java, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/home.htm, bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java
get User List based on user approval status for manage users page and pending approvals page
=> get User List based on user approval status

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/ActiveCollectionController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserApprovalController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/CollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java
@anut347 
Issue : https://github.com/ABenchM/abm/issues/212
Email api for approve/reject requests for user registration
=> Email for activate/deactivate

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserApprovalController.java, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/home.htm, bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java
Approve Reject - for pending requests page
https://github.com/ABenchM/abm/issues/201
=> Approve Reject - for pending requests page

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/AdminManageCollectionController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/CollectionDao.java
https://github.com/ABenchM/abm/issues/219
To get all public collections for admin controller for manage collections page
=> Get all public collections for manage collections

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/DeletePublicCollectionController.java
deletePublicCollection API now accepts list of public collections
=> deletePublicCollection API now accepts list of public collections

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserDetailsController.java, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/home.htm, bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaRoleMembers.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUser.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/RoleMembersDTO.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/UserDTO.java
changes to include role in getallsuerdetails for admin and get user info for user profile module
=> role info and getuserinfo

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/AdminManageCollectionController.java
Fixing the code for the issue
https://github.com/ABenchM/abm/issues/219
It is to return a list of collections for admin, for the "Manage Collections" page
=> Fixing getCollections for manage collection

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserApprovalController.java
Send approve/reject mail to user fix.
https://github.com/ABenchM/abm/issues/212
=> Send approve/reject mail to user fix

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserApprovalController.java, bnd-workspace/de.fraunhofer.abm.app/static/de.fraunhofer.abm/template/home.htm, bnd-workspace/de.fraunhofer.abm.app/web/controllers/CollectionController.js, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java
multiple approve/reject users
and
get user details for unapproved users fix
=> multiple approve/reject users

bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/DeletePublicCollectionControllerTest.java
DeletePublicCollectionControllerTest class is added with Testing of Delete Public collection
=> Test class DeletePublicCollectionController

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserApprovalController.java
=> Fix for multiple delete

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/DeletePublicCollectionController.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/ActivateCollectionControllerTest.java
https://github.com/ABenchM/abm/issues/230
@Chinmay-92 : Making the change to the name of the method in DeletePublicCollectionController , as discussed it was supposed to be post
=> Test case Activate/Deactivate public collections

bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/AdminUserDeleteControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UnlockUserControllerTest.java
Test cases for https://github.com/ABenchM/abm/issues/241,
https://github.com/ABenchM/abm/issues/246
=> Test cases for lock/unlock and deleteusers

bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java
Changes wrt get user role info enhancement.
https://github.com/ABenchM/abm/issues/250
=> Changes wrt get user role info enhancement

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/AbmApplication.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/BuildController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CollectionController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CommitController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/HermesController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/PinController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/VersionController.java, bnd-workspace/de.fraunhofer.abm.security/src/de/fraunhofer/abm/app/auth/Authorizer.java, bnd-workspace/de.fraunhofer.abm.security/src/de/fraunhofer/abm/app/auth/impl/UserAdminAuthorizer.java
=> anithas changes

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserDetailsController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaRoleMembers.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUser.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/RoleMembersDTO.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/UserDTO.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/GetUsersControllerTest.java, docs/abm.sql
Changes for get all users. Test Case will  be pushed by Chinmay in the next pull request which will also be created in sometime.
https://github.com/ABenchM/abm/issues/259
Changes in Files below:
UserDetailsController.java
JpaRoleMembers.java
JpaUser.java
JpaUserDao.java
UserDao.java
RoleMembersDTO.java
UserDTO.java
=> Changes for get all users

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/GetUserDetailsControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/GetUsersControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UserInfoControllerTest.java
changes for user registration(enhancement) and clean up for getUsers test
=> changes for user registration(enhancement)

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/AbmApplication.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/BuildController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CollectionController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CommitController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/HermesController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/PinController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/VersionController.java, bnd-workspace/de.fraunhofer.abm.security/src/de/fraunhofer/abm/app/auth/Authorizer.java, bnd-workspace/de.fraunhofer.abm.security/src/de/fraunhofer/abm/app/auth/impl/UserAdminAuthorizer.java, docs/abm.sql
@nguyenLisa : This is the pull request for "Multiple user login", allowing the "UserAdmin" to login, which we discussed during the meeting, 
I have created the an default "UserAdmin" as part of abm.sql, so that we have a "UserAdmin" role when we update abm.sql.
Issue link: https://github.com/ABenchM/abm/issues/185
The test case is the same login test which we already have .
All the controllers that we developed uses authorizer.requireRole("UserAdmin");
so the code changes were made
The changeRole() functionality will be pushed as part of further PR's
=> Login for "UserAdmin"

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaRoleProperties.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/RolePropertiesDTO.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/GetUserDetailsControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/GetUsersControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UserInfoControllerTest.java, docs/abm.sql
Changes to update password in role properties table and also the test cases which were pushed to the develop branch
=> Changes to update password in role properties table

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/ResetPasswordApprovalController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/ResetPasswordController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaResetTokenDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/ResetTokenDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/ResetPasswordControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UnlockUserControllerTest.java
This is the code for reset password functionality, which was reverted, so I am pushing it again
=> Reset password/Test case

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/BuildController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/PinController.java
Pull request
about: Handle security exception when restarting the server
about: When restarting the server and the user is logged in, we need to care of some security exceptions.
Yes. Issue #273 .
=> fx for issue #273

bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.security/.classpath, bnd-workspace/de.fraunhofer.abm.security/src/de/fraunhofer/abm/app/auth/impl/UserAdminAuthenticator.java
---
Name: Pull request
About: User should login only if user account is not locked.
---
Test classes for this PR will be same LoginTest.java 
Files modified : JpaUserDao, UserDao, UserAdminAuthenticator and build classpath(to include it in UserAdminAuthenticator.java
No dependency for frontend changes.
can be tested with same frontendpg branch
=> User should not login if account is locked

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/CollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UserInfoControllerTest.java
changes for delete user account by user with test case.
user logs in and go to user profile page and hit delete account.
changes for delete user account by user with test case
testDeleteUser in UserInfoControllerTest.java
changes in UserController.java, UserDao.java, JpaUserDao.java, CollectionDao.java, JpaCollectionDao.java, 
No Specific DB changes
=> changes for delete user account

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/ResetPasswordApprovalController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/ResetPasswordController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaResetToken.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaResetTokenDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/ResetTokenDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/ResetTokenDTO.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/ResetPasswordControllerTest.java
---
name: PR code changes for Forgot and Reset password
about: Suggest a change in the code of this project
---
Forgot and Reset password feature ( from home page )
sends reset email
and on click on link opens reset password page and updates password.
ResetPasswordControllerTest
Frontend branch to test: Frontendpg
Attached screenshot of passing Testcase
=> PR code changes for Forgot and Reset password

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaRoleProperties.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/RolePropertiesDTO.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UserInfoControllerTest.java
---
name: Update User Pull request
about: User can change profile information &/ change password
---
Steps to test Update User profile feature:
1. User should be logged in.
2. Select My Profile item from right top corner menu.
3. Change user data and click save changes to update user info.
4. enter old and new password to update password.
testUpdateUser method in UserInfoControllerTest.
**Frontend branch to test the functionality**
Frontendpg
Attached passing test cases:
=> Pull Request Update User ( user profile info & update password ) 

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CollectionController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollection.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/CollectionDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/CollectionDTO.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/ActivateCollectionControllerTest.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/ManagePublicCollectionTest.java, docs/abm.sql
a) To populate the "Manage Collections" for UserAdmin
-Changes are included in the method getCollections() in CollectionController.java
Test case: ManagePublicCollectionTest
b)To activate/deactivate Public collections
We can activate/deactivate the public collections.
The users will not be able to view deactivated public collections.
-Changes included:
New controller: ActiveCollectionController.java
Test case : ActivateCollectionControllerTest.java
Existing classes changed: JpaCollection.java
JpaCollectionDao.java
CollectionDao.java
CollectionDTO.java
Issues link: #196
#219
=> getallcollectionchanges and activate/deactivate public collections

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserAdminController.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/ManagePublicCollectionTest.java
name: Delete public collections Pull-request
List of functionalities contained in this pull request
Admin should be able to delete public collections.
Steps ->
login as admin
create public collections
go to manage collections from right top corner menu
select any number of collections and click on delete button / delete individual collection by icon button
List of the test cases
Test class: ManagePublicCollectionTest 
It has testDeleteCollection to delete public collection.
Frontend branch to be tested with
ManagePublicCollection
Test class passing
Attachment has passing Testcases
=> Pull Request for delete public collections(admin)

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserAdminController.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UserInfoControllerTest.java
Changes for admin delete user in manage users page for admin with test case
List of functionalities contained in this pull request
Changes for admin delete user in manage users page for admin
List of the test cases
testAdminDeleteUser in UserInfoControllerTest.java
Backend Changes
deleteAdminDeleteUsers added in UserAdminController.java
Database Changes
No specific DB changes
=> PR with changes for admin delete user

bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/UserInfoControllerTest.java
test case checking value of firstname is null
This was not checked in when we pushed code for register user since code to approve had to be in place if we had to check details of that user and call a get for the same.
https://github.com/ABenchM/abm/issues/267
Changes only in Test file UserInfoControllerTest.java
=> test case checking value of firstname is null

docs/abm.sql
As discussed,
for integration with delphi, a new table is introduced called "Project".
New table has created project with version id, project id and source columns.
=> Updating abm.sql for project table

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserApprovalController.java
code changes to enable mail sending on approve and reject users
Test cases in UserInfoControllerTest
UserApprovalController.java
uncommented sendApproveRejectEmail
None
=> code changes to enable mail sending on approve and reject users

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/VersionController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/CollectionDao.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/CollectionControllerTest.java
changes to get Version and collection details based on version id
**Is your pull request related to an issue? Please describe.**
New get api #299
get Version and collection details based on version id
testCollectionById in * CollectionControllerTest.java (Line no. 217 - 223)
PFA passing test cases(after clearing DB entries)
VersionController.java
JpaCollectionDao.java
CollectionDao.java
collection, version and commit tables to be empty to run the test case
=> changes to get Version and collection details based on version id

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserDetailsController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java, bnd-workspace/de.fraunhofer.abm.test.http/src/de/fraunhofer/abm/test/http/GetUsersControllerTest.java
changes for 'Admin should not be listed in manger user table'
https://github.com/ABenchM/abm/issues/331
Modified test cases testApprovedUsers and testNonApprovedUsers in GetUsersControllerTest.java
Changes in files UserDetailsController, UserDao, JpaUserDao.
None
=> changes for 'Admin should not be listed in manger user table'

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/UserController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao/src/de/fraunhofer/abm/collection/dao/UserDao.java
---
name: Pull request
about: One used email id cannot be used again for registering to the application.
---
**Is your pull request related to an issue? Please describe.**
Yes. #270
=> one email can not use again for registeration of account

bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/CollectionController.java, bnd-workspace/de.fraunhofer.abm.app/src/de/fraunhofer/abm/app/controllers/VersionController.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/configuration/default/configuration.json, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaCollectionDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaProject.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaUserDao.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaVersion.java, bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/src/de/fraunhofer/abm/collection/dao/jpa/JpaVersionDao.java, bnd-workspace/de.fraunhofer.abm.domain/src/de/fraunhofer/abm/domain/VersionDTO.java, bnd-workspace/de.fraunhofer.abm.useradmin.dao.jdbc/configuration/default/configuration.json
name: Pull request part 1 for Milestone 4 Project migration
about: Removing commits and replacing it with projects structure in all functionalities for milestone 4
List of functionalities contained in this pull request
1. Create new collection with dummy(hardcoded) projects ( instead of commits from crawlers )
2. Add dummy projects to existing collection
3. Delete project from a collection ( for private versions )
4. Derive version: name and derivedFrom parent is stored
5. Backend Changes
6. Same APIs with projects related logic instead of commits
Database Changes
already merged ( new table Project ).
Frontend branch to test this PR with : project_api_integration
=> Pull request for Milestone 4 ( reopened PR )

bnd-workspace/de.fraunhofer.abm.collection.dao.jpa/configuration/default/configuration.json, bnd-workspace/de.fraunhofer.abm.useradmin.dao.jdbc/configuration/default/configuration.json
=> reverting password credentials for login
